### ISSUE TITLE
Add shop field on demand new shop page

### ISSUE THREAD

**Issue by theo-code33** [theo-code33/bikeshop-organizer#105]
On page no shop
### TODO
- [x] Add input _**Nom**_ (_name_)
- [x] Add input _**Siret**_ (_siret_) with regex verification
- [x] Add input _**Adresse**_ (_address_)
- [x] Add input _**Code Postale**_ (_postalCode_)
- [x] Add input _**Ville**_ (_city_)
- [x] Add input _**Email**_ (_email_) with regex verification
- [x] Add input _**Numéro de Téléphone**_ (_phoneNumber_)
- [x] Add all data in email **_create-shop.hbs_**
