### ISSUE TITLE
Create Auth Guard by role

### ISSUE THREAD

**Issue by theo-code33** [theo-code33/bikeshop-organizer#17]
Create Auth guard who check the role of user

### Roles
- [x] user
- [x] shop
- [x] admin

### TODO
- [x] Create Roles decorator
- [x] Create RolesBased guard
- [x] Add Guard and role based on
      - User request
      - Shop request

> [!TIP]
> Check this documentation => https://shpota.com/2022/07/16/role-based-authorization-with-jwt-using-nestjs.html
