### ISSUE TITLE
Create Brand Resource

### ISSUE THREAD

**Issue by theo-code33** [theo-code33/bikeshop-organizer#31]
> [!IMPORTANT]
> Add relation with Bike

## TODO
- [x] Test request in postman without security
- [ ] Test request in postman with security

## Request
- [x] POST one
- [x] GET by shop
- [x] GET one by id 
- [x] PATCH one by id
- [x] DELETE one by id

#### Roles by Request
- [x] Admin, Shop and Employee for GET
- [x] Admin and Shop for DELETE,  PATCH, POST
#### Verification
- [ ] Check if shop who request is same id => Get by shop / Patch One by id

## Schema

![Image](https://github.com/theo-code33/bikeshop-organizer/assets/90395803/bb185961-a4cf-4bcd-9a0e-aa5db688a4c9)
