### ISSUE TITLE
Create Page Router

### ISSUE THREAD

**Issue by theo-code33** [theo-code33/bikeshop-organizer#51]
# TODO
- [x] Install React Router
- [x] Create routes path type
- [x] Create routes config file
- [ ] Create routes logic
