### ISSUE TITLE
Create Signup page

### ISSUE THREAD

**Issue by theo-code33** [theo-code33/bikeshop-organizer#57]
### TODO
- [x] Create page /signup
- [x] Create getAuth utils
- [x] Create router page restriction
