### ISSUE TITLE
Create Login page

### ISSUE THREAD

**Issue by theo-code33** [theo-code33/bikeshop-organizer#59]
### TODO
- [x] Create page /login
- [x] Implement getAuth method to check if user is already logged in and redirect if is it
- [x] Create Reset Password page
