### ISSUE TITLE
Create User update page

### ISSUE THREAD

**Issue by theo-code33** [theo-code33/bikeshop-organizer#67]
### TODO
- [x] Create User update page on route _/user_
- [x] Create update main informations
- [x] Create update password => ❗️Update token and user on update response❗️
