### ISSUE TITLE
Add creation of repair task category on Shop creation

### ISSUE THREAD

**Issue by theo-code33** [theo-code33/bikeshop-organizer#72]
### TODO
On shop creation, create also :
- [x] Repair Task Category
- [x] 3 Status => **À Faire**, **En cours**, **Terminé**
- [x] 3 Task Category Status with the 3 Status bellow
