### ISSUE TITLE
Create Settings page

### ISSUE THREAD

**Issue by theo-code33** [theo-code33/bikeshop-organizer#78]
### TODO
- [ ] Design **Settings** page
- [x] Create Settings page on _/settings_ path
- [x] Create _Prestations_ section
- [x] Create _Status_ section
