### ISSUE TITLE
Create Status form

### ISSUE THREAD

**Issue by theo-code33** [theo-code33/bikeshop-organizer#80]
### TODO
- [ ] Create _Update form_
- [x] Create _Create form_
- [ ] Create Drawer Compenent with paramters => Title, children, onSubmit, onClose, open, ButtonLeft, ButtonRight
- [ ] Add parameter _isUpdate_ to _Create form_
