### ISSUE TITLE
Create Clients page

### ISSUE THREAD

**Issue by theo-code33** [theo-code33/bikeshop-organizer#90]
### TODO
- [x] Create client page on path _/clients_
- [x] Create Clients listing
- [x] Create Client form dialog
