### ISSUE TITLE
Create Bike form

### ISSUE THREAD

**Issue by theo-code33** [theo-code33/bikeshop-organizer#96]
### TODO
- [x] Create Design
- [x] Create _create/update_
- [x] Create delete feature
- [x] Delete all bikes on Client delete
