### ISSUE TITLE
Create Dashboard Page

### ISSUE THREAD

**Issue by theo-code33** [theo-code33/bikeshop-organizer#98]
### TODO
- [x] Create page task category page
- [x] Get TaskCategory by id give in url param
- [x] Create Create/Update Feature
- [x] Create delete feature
- [x] Create listing and drag & drop task feature
- [ ] Add possibility to hide column status => for completed task or archived task
- [ ] Create TaskProductItem entity
